/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BContainer: typeof import('bootstrap-vue-next')['BContainer']
    BDropdownItemButton: typeof import('bootstrap-vue-next')['BDropdownItemButton']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BNavItemDropdown: typeof import('bootstrap-vue-next')['BNavItemDropdown']
    IBiCheck2: typeof import('~icons/bi/check2')['default']
    IBiCircleHalf: typeof import('~icons/bi/circle-half')['default']
    IBiCodeSlash: typeof import('~icons/bi/code-slash')['default']
    IBiInfoCircle: typeof import('~icons/bi/info-circle')['default']
    IBiMoonStarsFill: typeof import('~icons/bi/moon-stars-fill')['default']
    IBiSunFill: typeof import('~icons/bi/sun-fill')['default']
    NavbarHeader: typeof import('./components/NavbarHeader.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
